#spring.application.name=
#server.port=
#spring.mongodb.uri=
#spring.mongodb.database=
#
#
#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=
#
#spring.security.oauth2.client.registration.google.scope=
#jwt.secret=
#jwt.expiration-ms=
#app.frontend-url=
#spring.mail.host=
#spring.mail.port=
#
#spring.mail.username=
#spring.mail.password=
#
#spring.mail.properties.mail.smtp.auth=
#spring.mail.properties.mail.smtp.starttls.enable=
#cloudinary.cloud-name
#cloudinary.api-key
#cloudinary.api-secret
#spring.servlet.multipart.max-file-size=
#spring.servlet.multipart.max-request-size=

