spring.application.name=mongo
server.port=8081
spring.mongodb.uri=mongodb+srv://emadpumex:ynqH5OzKNCqAOAvD@cluster0.vwbppq3.mongodb.net/myapp?appName=Cluster0
spring.mongodb.database=myapp
spring.security.user.name=admin
spring.security.user.password=emad

